# Generated by Django 6.0 on 2026-01-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='language',
            field=models.CharField(default='বাংলা', help_text='Language of the quiz', max_length=50),
        ),
    ]
