# Generated by Django 6.0 on 2026-01-17 22:54

from django.db import migrations


def set_default_language(apps, schema_editor):
    """Set default language for any Quiz records with NULL language"""
    Quiz = apps.get_model('core', 'Quiz')
    Quiz.objects.filter(language__isnull=True).update(language='বাংলা')


def reverse_set_default_language(apps, schema_editor):
    """Reverse migration - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz_language'),
    ]

    operations = [
        migrations.RunPython(set_default_language, reverse_set_default_language),
    ]
